image: node:alpine

cache:
  paths:
    - ~/.npm
    - .jest

stages:
  - test
  - deploy

before_script:
  - yarn install

jest-tests:
  stage: test
  script:
    - yarn test --ci

expo-deployments:
  stage: deploy
  only:
    - master
  script:
    - apk add --no-cache bash
    - npx yarn global add expo-cli
    - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - npx expo publish --non-interactive